# Generated by Django 5.1 on 2025-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_alter_entreprise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
