# Generated by Django 5.1 on 2025-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
